### ISSUE TITLE
CmakeLists missing link

### ISSUE THREAD

**Issue by NatureLan-sudo** [z619850002/CVIDS#1]
hi , I git your code and find that the CmakeLists got some wrong. Can you give a fix?
 This multi-slam system is distributed or centralized?

**Comment by z619850002** [comment]
This is a centralized framework. For the compiling error, can you offer the detailed error log?

**Comment by NatureLan-sudo** [comment]
> This is a centralized framework. For the compiling error, can you offer the detailed error log?

Thank you for your reply, it's due to my mistake.

Is there a corresponding paper for this code?

**Comment by z619850002** [comment]
Our paper is still under review. Once it has been accepted, the relevant link will be offered immediately.

**Comment by lantianran** [comment]
> Our paper is still under review. Once it has been accepted, the relevant link will be offered immediately.
thank you for your reply. There is another question. It is found in Cmakelists that this project needs the support of CUDA. Do we need to install CUDA and whether the project can be independent of CUDA?

**Comment by NatureLan-sudo** [comment]
> Our paper is still under review. Once it has been accepted, the relevant link will be offered immediately.


thank you for your reply. There is another question. It is found in Cmakelists that this project needs the support of CUDA. Do we need to install CUDA and whether the project can be independent of CUDA?

**Comment by z619850002** [comment]
The current implementation of the dense mapping module is based on  CUDA. So maybe you can delete the dense mapping component to remove the dependent on CUDA, or just re-implement it (the speed will be unsatisfactory)
