### ISSUE TITLE
/home/kyrie开头的文件

### ISSUE THREAD

**Issue by Flanture** [z619850002/CVIDS#3]
作者您好，例如在src/server_pose_graph.cpp中就有两行代码：
    string aImageFilename = "/home/kyrie/Documents/DataSet/CoVins/Loop/image_"+  aIndex1   + ".jpg";
    string aPoseFilename = "/home/kyrie/Documents/DataSet/CoVins/Loop/pose_"+  aIndex1   + ".txt";
    这里能否提供或者介绍一下文件是什么呢？

**Comment by z619850002** [comment]
Most of these files are used for assisting experiments or just debugging during the review of the paper, and I temporarily wrote them using absolute path on my computer, which should not affect the normal operation logic of the program. You can also delete them all. On account of the early completion of this work and the long review cycle, at this stage, I apologize  that I no longer have time to reorganize or polish the code now.
